#!/bin/bash

# Run npm test command
echo "Running npm test..."
npm test

if [ $? -ne 0 ]; then
    echo "Tests failed. Aborting commit."
    exit 1
else
    echo "Tests passed. Committing changes..."
    exit 0
fi
#
#
#
#
#
